StylesPath = .github/styles
MinAlertLevel = suggestion

Packages = Google, proselint, write-good

[*.md]
BasedOnStyles = Vale, Google, proselint, write-good

# Disable rules that conflict with EVES writing conventions
Google.Acronyms = NO
Google.We = NO
Vale.Spelling = NO
