name: Gitbook Action

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Gitbook Action
        uses: ZanderZhao/gitbook-action@v1.2.4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          time_zone: Europe/Berlin
          source_branch: main
          source_dir: EVES
          source_edit_time: true
          publish_commit_message: ${{ github.event.head_commit.message }}
          publish_branch: gh-pages
          publish_dir: .
