name: Gitbook Action

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Gitbook Action
        uses: ZanderZhao/gitbook-action@v1.2.4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          time_zone: Europe/Berlin
          source_branch: main
          source_dir: EVES
          source_edit_time: true
          publish_commit_message: ${{ github.event.head_commit.message }}
          publish_branch: gh-pages
          publish_dir: .
