name: Prose Lint

on:
  pull_request:
    paths:
      - "**/*.md"
      - ".vale.ini"

jobs:
  vale:
    name: Vale
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Vale
        uses: errata-ai/vale-action@d89dee975228ae261d22c15adcd03578634d429c # v2.2.0
        with:
          reporter: github-pr-check
          fail_on_error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
